
include: package:flutter_lints/flutter.yaml

linter:
  rules:

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "build/**"
    - "script/**"
    - "lib/generated/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 30
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 300
  rules:
    # - avoid-ignoring-return-values
    # - avoid-late-keyword
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions
    # - avoid-non-null-assertion
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-casts
    - avoid-unused-parameters
    - avoid-unnecessary-type-assertions
    - binary-expression-operand-order
    - double-literal-format
    - member-ordering
    - member-ordering-extended
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    # - no-equal-arguments
    - no-equal-then-else
    # - no-magic-number
    - no-object-declaration
    - prefer-conditional-expressions
    # - prefer-correct-identifier-length
    - prefer-correct-type-name
    - prefer-first
    - prefer-last
    # - prefer-match-file-name
    - prefer-trailing-comma
  rules-exclude:
    - lib/generated/**