name: simple_kalman
description: A project to implement a one-dimensional Kalman filter in Dart language

repository: https://github.com/leech001/SimpleKalman/tree/main
issue_tracker: https://github.com/leech001/SimpleKalman/issues
homepage: https://github.com/leech001/SimpleKalman

version: 1.0.2

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.7.0'

dev_dependencies:
 flutter_lints: ^2.0.1
 dart_code_metrics: ^5.7.0
 test: ^1.24.0
