name: simple_kalman
description: A project to implement a one-dimensional Kalman filter in Dart language

repository: https://github.com/leech001/SimpleKalman/tree/main
issue_tracker: https://github.com/leech001/SimpleKalman/issues
homepage: https://github.com/leech001/SimpleKalman

version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
 flutter_lints: ^1.0.4
 dart_code_metrics: ^4.10.1
 test: ^1.20.1
