name: simple_kalman
description: A project to implement a one-dimensional Kalman filter in Dart language

repository: https://github.com/leech001/SimpleKalman/tree/main
issue_tracker: https://github.com/leech001/SimpleKalman/issues
homepage: https://github.com/leech001/SimpleKalman

version: 1.0.0

environment:
  sdk: ">=2.15.0-178.0.dev <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.0
  test: ^1.16.8